# Generated by Django 4.0 on 2022-01-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel_delete_samplemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='titel',
            new_name='title',
        ),
    ]
